interface Props {
  disabled: boolean; measureCount: number; loopEnabled: boolean; loopStart: number; loopEnd: number; progressive: boolean; tempoPercent: number
  onLoopEnabledChange: (value: boolean) => void; onLoopStartChange: (value: number) => void; onLoopEndChange: (value: number) => void
  onProgressiveChange: (value: boolean) => void; onTempoPercentChange: (value: number) => void; onTranspose: (semitones: number) => void; onExport: () => void
  devices: MediaDeviceInfo[]; deviceId: string; latencyMs: number; noiseThreshold: number; onDeviceChange: (value: string) => void; onLatencyChange: (value: number) => void; onNoiseThresholdChange: (value: number) => void
  midiTracks: string[]; selectedMidiTrack: number; onMidiTrackChange: (index: number) => void
  calibrating: boolean; onCalibrate: () => void
  vocalRange: string; rangeSummary: string; suggestedTranspose: number; onVocalRangeChange: (value: string) => void; onApplySuggestedTranspose: () => void
  evaluationMode: 'pitch-rhythm' | 'solfege'; solfegeSystem: 'fixed' | 'movable'; solfegeModelReady: boolean; onSolfegeSystemChange: (value: 'fixed' | 'movable') => void; onPreloadSolfege: () => void
}

export function PracticeControls(props: Props) {
  const measures = Array.from({ length: Math.max(1, props.measureCount) }, (_, index) => index + 1)
  return <section className="practice-controls"><h2>Prática</h2><div>
    <fieldset disabled={props.disabled}><legend>Transposição</legend><button onClick={() => props.onTranspose(-12)}>−8ª</button><button onClick={() => props.onTranspose(-1)}>−1</button><button onClick={() => props.onTranspose(1)}>+1</button><button onClick={() => props.onTranspose(12)}>+8ª</button></fieldset>
    <fieldset disabled={props.disabled}><legend>Tessitura</legend><label>Voz <select value={props.vocalRange} onChange={(event) => props.onVocalRangeChange(event.target.value)}><option value="soprano">Soprano</option><option value="alto">Contralto</option><option value="tenor">Tenor</option><option value="bass">Baixo</option></select></label><span className="range-summary">Exercício: {props.rangeSummary}</span><button disabled={!props.suggestedTranspose} onClick={props.onApplySuggestedTranspose}>{props.suggestedTranspose ? `Aplicar ${props.suggestedTranspose > 0 ? '+' : ''}${props.suggestedTranspose} semitons` : 'Já está na tessitura'}</button></fieldset>
    <fieldset disabled={props.disabled}><legend>Repetir trecho</legend><label><input type="checkbox" checked={props.loopEnabled} onChange={(event) => props.onLoopEnabledChange(event.target.checked)} /> Ativar</label><label>De <select value={props.loopStart} disabled={!props.loopEnabled} onChange={(event) => props.onLoopStartChange(Number(event.target.value))}>{measures.map((measure) => <option key={measure}>{measure}</option>)}</select></label><label>até <select value={props.loopEnd} disabled={!props.loopEnabled} onChange={(event) => props.onLoopEndChange(Number(event.target.value))}>{measures.filter((measure) => measure >= props.loopStart).map((measure) => <option key={measure}>{measure}</option>)}</select></label></fieldset>
    <fieldset disabled={props.disabled}><legend>Andamento progressivo</legend><label><input type="checkbox" checked={props.progressive} onChange={(event) => props.onProgressiveChange(event.target.checked)} /> Aumentar após score ≥ 85%</label><label>Início <input type="range" min="40" max="100" step="5" value={props.tempoPercent} onChange={(event) => props.onTempoPercentChange(Number(event.target.value))} /><span>{props.tempoPercent}%</span></label></fieldset>
    <fieldset disabled={props.disabled || props.calibrating}><legend>Microfone e latência</legend><label>Entrada <select value={props.deviceId} onChange={(event) => props.onDeviceChange(event.target.value)}><option value="">Padrão do sistema</option>{props.devices.map((device, index) => <option key={device.deviceId} value={device.deviceId}>{device.label || `Microfone ${index + 1}`}</option>)}</select></label><label>Latência <input type="number" min="0" max="500" step="5" value={props.latencyMs} onChange={(event) => props.onLatencyChange(Number(event.target.value))} /> ms</label><label>Ruído <input type="number" min="1" max="100" step="1" value={Math.round(props.noiseThreshold * 1000)} onChange={(event) => props.onNoiseThresholdChange(Number(event.target.value) / 1000)} /></label><button onClick={props.onCalibrate}>{props.calibrating ? 'Calibrando…' : 'Calibrar automaticamente'}</button></fieldset>
    {props.evaluationMode === 'solfege' && <fieldset disabled={props.disabled}><legend>Solfejo</legend><label>Sistema <select value={props.solfegeSystem} onChange={(event) => props.onSolfegeSystemChange(event.target.value as 'fixed' | 'movable')}><option value="fixed">Dó fixo</option><option value="movable">Dó móvel</option></select></label><button onClick={props.onPreloadSolfege} disabled={props.solfegeModelReady}>{props.solfegeModelReady ? 'Modelo pronto' : 'Preparar reconhecimento'}</button></fieldset>}
    {props.midiTracks.length > 1 && <label>Pista/voz <select disabled={props.disabled} value={props.selectedMidiTrack} onChange={(event) => props.onMidiTrackChange(Number(event.target.value))}>{props.midiTracks.map((name, index) => <option key={`${name}-${index}`} value={index}>{name}</option>)}</select></label>}
    <button disabled={props.disabled} onClick={props.onExport}>Exportar JSON</button>
  </div></section>
}
